### ISSUE TITLE
Add controller and service components

### ISSUE THREAD

**Issue by homubee** [homubee/Jwebcrawler#1]
### Issue Description

기본 엔티티들에 관한 컨트롤러와 서비스 컴포넌트 작성 및 추가

### TODO

- [x] Member 부분 개발
- [x] Post 부분 개발
- [x] Comment 부분 개발
- [x] Role 부분 개발

### ETC.

기본 기능이 동작하도록만 추가하고 핵심 기능은 추후 고도화 예정
