### ISSUE TITLE
Documentation (Backend)

### ISSUE THREAD

**Issue by homubee** [homubee/Jwebcrawler#11]
### Issue Description

백엔드 개발 내용 문서화 (Swagger 문서 개선, 주석 작성, Readme 문서 작성 등)

### TODO

- [x] Swagger 문서 개선
- [x] 코드 주석 작성 및 개선
- [x] Readme 문서 추가

### ETC.

특이사항 없음
