### ISSUE TITLE
Setting frontend

### ISSUE THREAD

**Issue by homubee** [homubee/Jwebcrawler#13]
### Issue Description

프론트엔드 기본 세팅 (npm 모듈 설치, 기본 프로젝트 구성 요소 추가)

### TODO

- [x] npm 모듈 설치 (Redux, Axios, MUI)
- [x] 프로젝트 기본 요소 추가
- [x] CORS 설정 (localhost, vercel 연결)

### ETC.

특이사항 없음
