### ISSUE TITLE
Bug fix & Documentation

### ISSUE THREAD

**Issue by homubee** [homubee/Jwebcrawler#27]
### Issue Description

페이지네이션 total 버그 수정 및 Help 페이지 오타 수정, 기타 문서화

### TODO

- [x] 페이지네이션 total bug 수정
- [x] Help 페이지 오타 수정
- [x] 기본 정렬 순서 추가(최신순)
- [x] Readme 문서 갱신

### ETC.

특이사항 없음
